# description of this workflow, can be anything you want
name: Package and release

# we need to let GitHub know _when_ we want to release, typically only when we create a new tag.
# this will target only tags, and not all pushes to the master branch.
# this part can be heavily customized to your liking, like targeting only tags that match a certain word,
# other branches or even pullrequests.
on:
  push:
    tags:
      - '**'

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "release" is a job, you can name it anything you want
  release:

    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow
                                                 # for your own token, the name cannot start with "GITHUB_"

    # "steps" holds a list of all the steps needed to package and release our AddOn
    steps:

      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # gets git history for changelogs

      #- name: Package and release (ONE-ZIP)
      #  uses: BigWigsMods/packager@master

      - name: Package and release for Retail
        uses: BigWigsMods/packager@master
        with:
          args: -g retail -w 0

      - name: Package and release for Mists Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g mists -w 0

      - name: Package and release for Cata Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g cata -w 0

      - name: Package and release for Wrath Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath -w 0

      - name: Package and release for Burning Crusade Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc -w 0

      - name: Package and release for Classic Era
        uses: BigWigsMods/packager@master
        with:
          args: -g classic -w 0
